FDOS-268 Generic build step for package and service

diff --git a/.github/workflows/build-project.yaml b/.github/workflows/build-project.yaml
--- a/.github/workflows/build-project.yaml
+++ b/.github/workflows/build-project.yaml
@@ -1,10 +1,14 @@
-name: Build service workflow
-
+name: Build project workflow
+run-name: Build ${{ inputs.type }} - ${{ inputs.name }}
 on:
   workflow_call:
     inputs:
-      service_name:
-        description: "The name of the service to build"
+      build_type:
+        description: "The type of project to build (service, package)"
+        required: true
+        type: string
+      name:
+        description: "The name of the package to build"
         required: true
         type: string
       python_version:
@@ -33,10 +37,33 @@ on:
           type: string
 
 jobs:
-  build-service:
-    name: "Build service - ${{ inputs.service_name }}"
+  get-working-directory:
+    name: "Get working directory"
+    runs-on: ubuntu-latest
+    outputs:
+      working_directory: ${{ steps.get-working-directory.outputs.working_directory }}
+      build_directory: ${{ steps.get-working-directory.outputs.build_directory }}
+    steps:
+      - name: "Get working directory"
+        id: get-working-directory
+        run: |
+          if [[ "${{ inputs.build_type }}" == "service" ]]; then
+            echo "working_directory=services/${{ inputs.name }}" >> $GITHUB_OUTPUT
+            echo "build_directory=build/service/${{ inputs.name }}" >> $GITHUB_OUTPUT
+          elif [[ "${{ inputs.build_type }}" == "package" ]]; then
+            echo "working_directory=application/packages/${{ inputs.name }}" >> $GITHUB_OUTPUT
+            echo "build_directory=build/package/${{ inputs.name }}" >> $GITHUB_OUTPUT
+          else
+            echo "Invalid build type: ${{ inputs.build_type }}"
+            exit 1
+          fi
+
+  build-project:
+    name: "Build ${{ inputs.build_type }} - ${{ inputs.name }}"
     runs-on: ubuntu-latest
     environment: ${{ inputs.environment }}
+    needs:
+      - get-working-directory
     permissions:
       id-token: write
       contents: read
@@ -61,23 +88,26 @@ jobs:
         uses: asdf-vm/actions/install@v3.0.2
 
       - name: "Install project"
-        run: cd services/${{ inputs.service_name }} && make install
+        run: make install
+        working-directory: ${{ needs.get-working-directory.outputs.working_directory }}
 
       - name: "Run linting"
-        run: cd services/${{ inputs.service_name }} && make lint
+        run: make lint
+        working-directory: ${{ needs.get-working-directory.outputs.working_directory }}
 
       - name: "Run unit tests"
-        run: cd services/${{ inputs.service_name }} && make unit-test
+        run: make unit-test
+        working-directory: ${{ needs.get-working-directory.outputs.working_directory }}
 
-      - name: "Build service"
-        run:  |
-          poetry self add poetry-plugin-export
-          cd services/${{ inputs.service_name }} && make build
+      - name: "Build project"
+        run:  make build
+        working-directory: ${{ needs.get-working-directory.outputs.working_directory }}
         env:
-          SERVICE: ${{ inputs.service_name }}
+          SERVICE: ${{ inputs.name }}
+          PACKAGE: ${{ inputs.name }}
           PYTHON_VERSION: ${{ inputs.python_version }}
           APPLICATION_TAG: ${{ inputs.application_tag }}
-          ENVIRONMENT: ${{ inputs.environment }}
+          ENVIRNOMENT: ${{ inputs.environment }}
           REPO_NAME: ${{ inputs.repo_name }}
 
       - name: "Configure AWS Credentials"
@@ -88,11 +118,13 @@ jobs:
           multi_domain: false
 
       - name: "Publish artefacts to S3"
-        run: cd services/${{ inputs.service_name }} && make publish
+        run: make publish
+        working-directory: ${{ needs.get-working-directory.outputs.working_directory }}
         env:
-          SERVICE: ${{ inputs.service_name }}
+          SERVICE: ${{ inputs.name }}
+          PACKAGE: ${{ inputs.name }}
           COMMIT_HASH: ${{ inputs.commit_hash }}
-          ENVIRONMENT: ${{ inputs.environment }}
+          ENVIRNOMENT: ${{ inputs.environment }}
           REPO_NAME: ${{ inputs.repo_name }}
           WORKSPACE: ${{ inputs.workspace }}
           APPLICATION_TAG: ${{ inputs.application_tag }}
@@ -100,6 +132,6 @@ jobs:
       - name: "Publish artefacts to GitHub"
         uses: actions/upload-artifact@v4.6.1
         with:
-          name: ${{ inputs.service_name }}-artefacts
-          path: build/services/${{ inputs.service_name }}/
+          name: ${{ inputs.name }}-${{ inputs.build_type }}-artefacts
+          path: ${{ needs.get-working-directory.outputs.build_directory }}
           if-no-files-found: error
