FDOS-223 add a new job for the cache clearance

diff --git a/.github/workflows/deploy-project.yaml b/.github/workflows/deploy-project.yaml
--- a/.github/workflows/deploy-project.yaml
+++ b/.github/workflows/deploy-project.yaml
@@ -53,22 +53,6 @@ jobs:
       - name: "Checkout code"
         uses: actions/checkout@v4
 
-      - name: "Install asdf"
-        uses: asdf-vm/actions/setup@v3.0.2
-        with:
-          asdf_branch: v0.15.0
-
-      - name: "Cache asdf tools"
-        id: asdf-cache
-        uses: actions/cache@v4
-        with:
-          path: ~/.asdf
-          key: asdf-${{ runner.os }}-${{ hashFiles('.tool-versions') }}
-
-      - name: "Install tools from .tool-versions"
-        if: steps.asdf-cache.outputs.cache-hit != 'true'
-        uses: asdf-vm/actions/install@v3.0.2
-
       - name: "Configure AWS Credentials"
         uses: ./.github/actions/configure-credentials
         with:
@@ -102,6 +86,40 @@ jobs:
           WORKSPACE: ${{ inputs.workspace }}
           APPLICATION_TAG: ${{ inputs.application_tag }}
           DEPLOYMENT_ENVIRONMENT: ${{ inputs.deployment_environment }}
+
+  clear-cache:
+    name: "Build ${{ inputs.build_type }} - ${{ inputs.name }}"
+    runs-on: ubuntu-latest
+    environment: ${{ inputs.deployment_environment }}
+    needs:
+      - build-project
+    permissions:
+      id-token: write
+      contents: read
+    steps:
+      - name: "Checkout code"
+        uses: actions/checkout@v4
+
+      - name: "Configure AWS Credentials"
+        uses: ./.github/actions/configure-credentials
+        with:
+          aws_account_id: ${{ secrets.ACCOUNT_ID }}
+          aws_region: ${{ vars.AWS_REGION }}
+          multi_domain: false
+
+      - name: "Get directories"
+        id: get-directories
+        run: |
+          if [[ "${{ inputs.build_type }}" == "service" ]]; then
+            echo "working_directory=services/${{ inputs.name }}" >> $GITHUB_OUTPUT
+            echo "build_directory=build/services/${{ inputs.name }}" >> $GITHUB_OUTPUT
+          elif [[ "${{ inputs.build_type }}" == "package" ]]; then
+            echo "working_directory=application/packages/${{ inputs.name }}" >> $GITHUB_OUTPUT
+            echo "build_directory=build/packages/${{ inputs.name }}" >> $GITHUB_OUTPUT
+          else
+            echo "Invalid build type: ${{ inputs.build_type }}"
+            exit 1
+          fi
 
       - name: "Invalidate CloudFront Cache"
         run: make invalidate-cloudfront-cache
