FDOS-285 Check outcome of apply

diff --git a/.github/workflows/pipeline-deploy-fdos-application.yaml b/.github/workflows/pipeline-deploy-fdos-application.yaml
--- a/.github/workflows/pipeline-deploy-fdos-application.yaml
+++ b/.github/workflows/pipeline-deploy-fdos-application.yaml
@@ -130,11 +130,17 @@ jobs:
     needs:
       - metadata
       - deploy-infrastructure-apply
+    if: always()
     runs-on: ubuntu-latest
     steps:
       - name: Check deployment status
         run: |
-          echo "Deployment succeeded."
+          if [ "${{ needs.deploy-infrastructure-apply.outputs.apply_result }}" != "true" ]; then
+            echo "Deployment failed. Please check the logs."
+            exit 1
+          else
+            echo "Deployment succeeded."
+          fi
   slack-notifications:
     name: "Send Notification to Slack"
     needs:
